# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Pankaj Kumar
title: Senior Software Engineer
email: pankaj.gat@gmail.com
website: pankajgangwar.github.io

# Social links
twitter_username: 
github_username:  pankajgangwar
# dribbble_username: jekyll
facebook_username: pankajgangwar
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: pankaj-kumar-a747ab71
stackoverlow_username: pankaj
leetcode_username: pkumar7
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pankaj and I'm a Senior Software Engineer at HARMAN International. As an engineer, I have gained experience in connected-car 
  technologies, automotive and enterprise mobility.
  Apart from regular office work, I like solving complex algorithmic problems on competetive programming platforms . I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Android with Java, Python, C++</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in software engineering some of my other interests and hobbies are:
   - Competetive programming @LeetCode, HackerRank, CodeForces
   - Content creator and mentor @LeetCode, world's leading online platform for learning programming and algorithms
   - Running Marathon
   - Trekking

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
